#e constants.py
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 400
CELL_EVEN_COLOR = (179, 225, 172)
CELL_ODD_COLOR = (115, 195, 108)
CELL_SIZE = 60
GRID_SIZE = (10, 10)  # Example size
GRID_WIDTH, GRID_HEIGHT = GRID_SIZE[0] * CELL_SIZE, GRID_SIZE[1] * CELL_SIZE
START_POSITION = (0, 0)
POLICEMAN_START_POSITION = (5, 5)
POLICEMAN_DIRECTION = "random"  # Options: "up", "down", "random"

ALGORITHM = "Q-Learning"  # Options: "Q-Learning", "SARSA"
TRAINING_GAMES = 1000
PLAYING_GAMES = 10

EPSILON = 0.1
ALPHA = 0.1
GAMMA = 0.9

CELL_SIZE = 50
WINDOW_TITLE = "Reinforcement Learning Game"
